services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:latest
    container_name: reverse-proxy
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http3
      - --log.level=INFO

      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false # Do not expose containers unless explicitly told so

      - --api=true # Enable dashboard
      - --api.debug=true
      #- --api.insecure=true
      #- --certificatesresolvers.le.acme.tlschallenge=true
      #- --certificatesresolvers.le.acme.email=admin@ddev.site #  cert resolvers
      #- --certificatesResolvers.le.acme.storage=/ssl/acme.json
    restart: always
    ports:
      - 80:80/tcp
      - 80:80/udp
      #- 443:443/tcp
      #- 443:443/udp
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      #- ${PWD}/ssl:/ssl
    labels:
      traefik.enable: true

      # Dashboard
      traefik.http.routers.reverse-proxy.rule: Host(`marketing101.ddns.net`)
      traefik.http.routers.reverse-proxy.entrypoints: web
      traefik.http.routers.reverse-proxy.service: api@internal
      #traefik.http.routers.reverse-proxy.tls: true
      #traefik.http.routers.reverse-proxy.tls.certresolver: le
      #traefik.http.routers.reverse-proxy.middlewares: dashboard
      traefik.http.middlewares.dashboard.basicauth.users: user:$$apr1$$pNNqxCSq$$nwlnzsOf4skk6gjq246dB1


      # SECURITY MIDDLEWARE named "hstsx"
      #traefik.http.middlewares.hstsx.headers.stsincludesubdomains: true
      #traefik.http.middlewares.hstsx.headers.stspreload: true
      #traefik.http.middlewares.hstsx.headers.stsseconds: 31536000
      #traefik.http.middlewares.hstsx.headers.forcestsheader: true
      #traefik.http.middlewares.hstsx.headers.customframeoptionsvalue: sameorigin
      #traefik.http.middlewares.hstsx.headers.browserxssfilter: true
      #traefik.http.middlewares.hstsx.headers.sslredirect: true
      #traefik.http.middlewares.hstsx.headers.contenttypenosniff: true
    networks:
      - default

